### ISSUE TITLE
Add quick suggestions

### ISSUE THREAD

**Issue by ljubadr** [ctf0/laravel-goto-env#1]
This is a feature request

Would it be possible to add quick suggestions (autocomplete) for `.env` file? It would be nice that when I type `env('` quick suggestion kicks in and shows all possible environment variables from the `.env` file

I don't anything about developing vscode extensions but I tried to find code example for quick suggestions and I found [this example](https://github.com/microsoft/vscode-extension-samples/blob/main/completions-sample/src/extension.ts). I hope it helps :smile:

**Comment by ctf0** [comment]
for this i use https://marketplace.visualstudio.com/items?itemName=amiralizadeh9480.laravel-extra-intellisense instead

**Comment by ljubadr** [comment]
> for this i use https://marketplace.visualstudio.com/items?itemName=amiralizadeh9480.laravel-extra-intellisense instead

That works for me :smile: Thanks for the suggestion!
