### ISSUE TITLE
Update follow up

### ISSUE THREAD

**Issue by ljubadr** [ctf0/laravel-goto-env#2]
Hey, I created this as a follow up to [this issue in goto config](https://github.com/ctf0/laravel-goto-config/issues/5)

I've tested `goto env` locally and now it's showing following error notification

```
Unable to open '.env': File not found.
```

even though the file is there. If I click to create file it shows

```
Unable to write file '//Users/Users/<project>/api/.env' (NoPermissions (FileSystemError): Error: EACCES: permission denied, mkdir '/Users/Users')
```

When I revert the version back to `0.2.3` it works without any issues. I'm not sure why latest [update causes issue](https://github.com/ctf0/laravel-goto-env/commit/c0a10879ecbd8e1411898010c55dce4f669f236d) but it's probably better to revert change

**Comment by ctf0** [comment]
its working correctly on my machine, try to remove & reinstall

**Comment by ljubadr** [comment]
I tested on my home computer that runs ubuntu 20.04 and I see the same error. I uninstalled and installed the extension again and the error is still there

I tested again by starting vscode with new empty user and extensions folder, in which case it behaves as fresh vscode install

```bash
code --user-data-dir ~/vscode_profiles/laravel-goto-env --extensions-dir ~/vscode_profiles/laravel-goto-env-extensions
```
Note that I didn't even have folder `~/vscode_profiles` on my computer before I ran this

I still get the same error

I tested current and "new" vscode on few legacy laravel projects that I have and I also tested on [example repo](https://github.com/ljubadr/laravel-goto-config-remote-container-crash) that I created for previous issue. It just contains fresh laravel project and `devcontainer` setup

I keep getting the same error and it happens on both macbook pro and ubuntu

```
Unable to open '.env': File not found.
```

I checked and both extension versions `0.2.3` and `0.2.4` generate same link on hover

```
vscode://ctf0.laravel-goto-env//<absolute-path-to-file>#<env-name>
```

If this is happening only on my side then no worries. I don't have time to dig into this right now but I'll take some time tomorrow or after tomorrow to look into this and I'll report back what I find :+1:

**Comment by ljubadr** [comment]
I did a quick test and it looks like `//` in `vscode://ctf0.laravel-goto-env//<absolute-path-to-file>#<env-name>` causes the issue. It's before `<absolute-path-to-file>`

I've used debug mode and added quick `path = path.replace('//', '/')` before

```
commands.executeCommand('vscode.open', Uri.file(path))
```
and in that case it works

**Comment by ctf0** [comment]
plz try this 
- remove the `.zip` 
- manually install it
- reply back

[laravel-goto-env-0.2.5.vsix.zip](https://github.com/ctf0/laravel-goto-env/files/8356081/laravel-goto-env-0.2.5.vsix.zip)

**Comment by ljubadr** [comment]
I just tested `vsix` on mac and ubuntu and everything looks good :+1: 

I tested both on host and in remote containers

**Comment by ctf0** [comment]
good, i will publish them all today, thanks again 🤙
