### ISSUE TITLE
Upload the extension on Open VSX

### ISSUE THREAD

**Issue by GoodM4ven** [ctf0/laravel-goto-env#3]
Hey there,

Would you kindly make the extension available on [VSX](https://open-vsx.org/), so we can download it in [VSCodium](https://vscodium.com/)?

Also, if you're pro-privacy, could you just do the same to your other awesome extensions:

- [Env Symbol Provider](https://github.com/ctf0/env-symbol-provider)
- [Laravel Goto Config](https://github.com/ctf0/laravel-goto-config)
- [Laravel Goto Lang](https://github.com/ctf0/laravel-goto-lang)
- [Laravel Goto View](https://github.com/ctf0/laravel-goto-view)
- [Php Array Symbol Provider](https://github.com/ctf0/vscode-php-array-symbol-provider)

Thanks.

**Comment by ctf0** [comment]
will see what i can do, thanks
