### ISSUE TITLE
does not working

### ISSUE THREAD

**Issue by ahmedzu** [ctf0/laravel-goto-env#4]
does not working !!
when i have blade file and have this code inside it -> {{ env('APP_DEBUG') }}
when i hover nothing happen 
also when i press ctrl and click nothing happen too

**Comment by ctf0** [comment]
r u using docker ?
have u configured the pkg correctly ?
check the editor dev tools for any errors.

**Comment by ahmedzu** [comment]
no iam not using docker
every other (laravel goto ..) Extensions working fine except this Extension not working
![Screenshot 2024-05-14 083634](https://github.com/ctf0/laravel-goto-env/assets/11975016/ce9f91b6-a16e-4f27-860f-d87aba8a2394)

**Comment by ctf0** [comment]
i tested it and its working
<img width="839" alt="image" src="https://github.com/ctf0/laravel-goto-env/assets/7388088/c8f9a066-b47d-4cb1-9993-2c207988f9e2">

**Comment by ahmedzu** [comment]
strange !!
So i think maybe there is an conflict with another extension , i will try to uninstall all other extensions and see
By the way, I loved your editor looks
Can you share the extensions you use?
Just paste the following code into your editor terminal (powershell)

(code --list-extensions | % { "--install-extension $_" } )-join " " -replace '^.{0}','code '

and Please share the results with me here , so i can install all extensions that you use

**Comment by ctf0** [comment]
i got `parse error near `}'` but anyway here are the ext from the screenshot

- https://marketplace.visualstudio.com/items?itemName=MartinaTorce.beautiful-theme with custom colors
  ```json
  "[Dark Pink Theme]": {
      "activityBar.foreground": "#ffffff",
      "actionBar.toggledBackground": "#7a485c",
      "activityBar.inactiveForeground": "#492c38",
      "breadcrumb.background": "#2e121e",
      "dropdown.background": "#7a485c",
      "editorStickyScrollHover.background": "#7a485c",
      "editorStickyScroll.background": "#492c38",
      "input.background": "#7a485c",
      "pickerGroup.border": "#7a485c",
      "settings.checkboxBackground": "#ff0060",
      "settings.checkboxBorder": "#ff0060",
      "statusBarItem.remoteBackground": "#2e121e",
      "statusBarItem.remoteForeground": "#ffffff",
      "tab.hoverBackground": "#7a485c",
      "tab.inactiveBackground": "#5c3646",
      "terminal.background": "#3b1727",
      "tree.indentGuidesStroke": "#e6acc580",
  },
  ```
- https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade
- https://marketplace.visualstudio.com/items?itemName=ctf0.inline-fold-new
  ```json
  "inlineFold.unfoldedOpacity": 1,
  "inlineFold.regex": "(class|className|style|xmlns|[^\\w]d)=[\"]([^`'\"}]{15,})[\"]",
  "inlineFold.regexGroup": "2",
  "inlineFold.maskCss": "color:#ffd200;background:#ffd20030;padding:4px;border-radius:4px;",
  "inlineFold.maskChar": "◦◦◦",
  ```
